version: '3.8'
services:
  nginx-proxy:
    build: .
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl
    networks:
      - app-network
networks:
  app-network:
    driver: bridge